baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "hugo-book"

googleAnalytics = "G-9WVGW5YY5G"

# Book configuration
disablePathToLower = true
enableGitInfo = true


# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1


[caches]
[caches.images]
dir = ':cacheDir/images'


[languages]
[languages.en]
contentDir = 'content/english'
languageName = 'English'
weight = 10
[languages.ko]
contentDir = 'content/korean'
languageName = '한국어'
weight = 20
